image: node:14

pipelines:
  default:
    - step:
        name: Build and Test Core Library
        script:
          - echo "Checking out repository..."
          - git clone https://modernsoftwaredevelopmen-admin@bitbucket.org/nclexpower/ncturbo.git
          - apt-get update && apt-get install -y jq
          - echo "Removing local dependencies from package.json..."
          - cd packages/core-library
          - jq 'del(.devDependencies["@repo/eslint-config"]) | del(.devDependencies["@repo/typescript-config"])' package.json > temp.json && mv temp.json package.json
          - echo "Installing dependencies for core-library..."
          - npm install
          - echo "Running tests with coverage for core-library..."
          - npm run test -- --coverage
          - echo "Uploading coverage reports to Codecov..."
          - bash <(curl -s https://codecov.io/bash) -t $codecov_bitbucket -f ./packages/core-library/coverage/**/coverage-final.json -n codecov-core-library

    - step:
        name: Deploy to Vercel
        script:
          - echo "Deploying simulator to Vercel..."
          - cd apps/simulator
          - npx vercel --token $BBKT_VERCEL_TOKEN
          - echo "Deploying web-backoffice-generic to Vercel..."
          - cd ../web-backoffice-generic
          - npx vercel --token $BBKT_VERCEL_TOKEN
          - echo "Deploying web-customer to Vercel..."
          - cd ../web-customer
          - npx vercel --token $BBKT_VERCEL_TOKEN
