version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    command: npm start
