name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test_core_library:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies for core-library
        run: |
          cd packages/core-library
          npm install

      - name: Run tests with coverage for core-library
        run: |
          cd packages/core-library
          npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: [build_and_test_core_library]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
